---
title: "People"
---

## Current Members

### PhD Students

- Shuaishuai Li
- Alexandra McCallum
- Jake Harvey
- Xiaotian Hua
- Luis De Gracia-Núñez
- Tess Morelli

### MSc Students

- Sarah Junk
- Micah Pavlidis
- Eleanor Grace Dunleavy

---

## Past Members

### Postdocs

- Elliot Dreujou
- [Justin Marleau](http://jmarleau.ca/)
- [Ramesh Arumugam](https://www.researchgate.net/profile/Ramesh_Arumugam4)
- Geoffrey Cook
- Dominique Gravel
- Philippe Girard
- Heike Link
- Tri Nguyen Quang
- Yuxiang Zhang
- Rémi Daigle
- Pierre Chuard

### PhD Alumni

- Brendon McGuinness — PhD 2025
- [Nicole Knight](http://nicolesknight.weebly.com/) — PhD 2023
- [Tianna Peller](http://chone2.ca/people/tianna-peller/) — PhD 2021
- [Ridouan Bani](https://www.researchgate.net/profile/Ridouan_Bani) — PhD 2020
- [Chantal Hutchison](http://qcbs.ca/members/students/?stu_profile=1574) — PhD 2020
- Julian Xue — PhD 2016
- Eric Pedersen — PhD 2015
- Justin Marleau — PhD 2014
- Nicolas Le Corre — PhD 2013
- Anaïs Lacoursière-Roussel — PhD 2013
- Kecia Kerr — PhD 2012
- Tarik C. Gouhier — PhD 2010
- Oscar Puebla — PhD 2009
- Alex Tewfik — PhD 2005

### MSc Alumni

- Chiara Babinski — MSc 2026
- Fiona Madsen — MSc 2026
- Félix Lauzon — MSc 2022
- Alexandra McCallum — MSc 2023
- Russell Milne — MSc 2018
- Julien Massé Jodoin — MSc 2017
- Laurence Paquette — MSc 2015
- Cesar Largaespada — MSc 2010
- Christian Brazeau — MSc 2009
- Geneviève Smith — MSc 2007
- Pradeep Pillay — MSc 2007
- Filip Petrovic — MSc 2007
